version: '3.9'
services:
  mlflow:
    image: chck/mlflow:1.28.0
    build:
      context: .
      cache_from:
        - chck/mlflow:1.27.0
    command: [
      "--static-prefix=/user1",
      "--gunicorn-opts=--worker-class=gevent --access-logfile=- --timeout=180 --log-level=debug",
    ]
    ports:
      - "5000:5000"
    env_file:
      - .env
